name: flutter_to_arch
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  yaml:
  io:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  flutter_to_arch:

platforms:
  linux:
